# location for all generated files
basename: gtdb95-evolpaths

output_dir: gtdb95-evolpaths

# type of input data (protein or nucleotide)
input_type: protein

lineages_csv: gtdb-r95-reps.lineages.protein-filenames.reordered.csv

evolpaths: gtdb-r95-reps.pathinfo.tsv

# directory in which genome filenames live
data_dir: /group/ctbrowngrp/gtdb-r95 #/protein_faa_reps -folder is already part of filename

alphabets:
  nucleotide:
    ksizes: [21,31,51]
    scaled: 1000
    alpha_cmd: "--dna"
    moltype: "dna"
    ksize_multiplier: 1
  protein:
    ksizes: [7,9,10,11]
    scaled: 100
    alpha_cmd: "--protein"
    moltype: "protein"
    ksize_multiplier: 3
  dayhoff:
    ksizes: [15,17,19]
    scaled: 100
    alpha_cmd: "--dayhoff"
    moltype: "dayhoff"
    ksize_multiplier: 3
  hp:
    ksizes: [30,33,35]
    scaled: 100
    alpha_cmd: "--hp"
    moltype: "hp"
    ksize_multiplier: 3
